### ISSUE TITLE
Improve GetWeights

### ISSUE THREAD

**Issue by leonardoaraujosantos** [leonardoaraujosantos/DLMatFramework#25]
## Introduction
Improve by calculating (from it's parameters) or just by passing inside the layer the weights information.

**Comment by dpackwood** [comment]
I think actually this cannot be fixed, since at least at creation any BaseLayer might not have a DeepLearningModel to even check its own weights

**Comment by leonardoaraujosantos** [comment]
Hi @dpackwood I've added the method getWeightShape on base Layer, so from the layer container (or layer graph) you can get the weight shape

### From DeepLearningModel object
``` matlab
grf = net.getLayerContainer.getGraph();
grf(2).objRef.getWeightShape()
```

### From the layer container
``` matlab
layers.getLayerFromIndex(2).getWeightShape()
```
