### ISSUE TITLE
Implement Batch Norm layer on CPU

### ISSUE THREAD

**Issue by leonardoaraujosantos** [leonardoaraujosantos/DLMatFramework#43]
## Introduction
Implement Forward backward propagation on CPU. Also create mex interface to check results on matlab

**Comment by Burton2000** [comment]
**Loss graph**
Vanilla - Blue
Dropout - Orange
Batch Norm - Yellow
![losses_working](https://cloud.githubusercontent.com/assets/17595269/24705551/6625e668-1a04-11e7-971b-7857dcf14344.PNG)

All working as expected.
