### ISSUE TITLE
Create Average Pool Layer

### ISSUE THREAD

**Issue by leonardoaraujosantos** [leonardoaraujosantos/DLMatFramework#7]
## Introduction
Implement the Average Pooling layer:
![avgpooling](https://cloud.githubusercontent.com/assets/898383/23612322/f138fb0e-0272-11e7-89bc-f0c2d86b1401.png)

## Where is used
Normally the AVG pooling layer is used just before the FC layers, by averaging the whole spatial information. The idea is to use less weights and still retain some of the spatial information. This technique is used on the residual networks.
![avgpoolinggraph](https://cloud.githubusercontent.com/assets/898383/23612710/55f9a056-0274-11e7-90ee-ef30cd2d7dad.png)

## Task
* Create new layer
* Create Test with layer alone
* Create Test with CONVNET using avg pooling one layer before the FC layers

## References
* [Intro video, Hugo Larochelle](https://www.youtube.com/watch?v=I-JKxcpbRT4&list=PL6Xpj9I5qXYEcOhn7TqghAJ6NAPrNmUBH&index=73)
* [Backprop video, Hugo Larochelle](https://www.youtube.com/watch?v=cDdpwAIsuD8&index=74&list=PL6Xpj9I5qXYEcOhn7TqghAJ6NAPrNmUBH)

**Comment by Burton2000** [comment]
https://github.com/leonardoaraujosantos/DLMatFramework/commit/4c0a77b31f343dd5b91fe7030b3a8af5f9910d44

Initial commit of average pooling

**Comment by leonardoaraujosantos** [comment]
Super cool @Burton2000, check about docs and comments on code :1st_place_medal: 
Also on the tests there is this flag that enable gradient check

**Comment by leonardoaraujosantos** [comment]
## Current results
Tested with the gradient check
